import { Card, PageHeader } from '@/components/admin/ui';

const TYPES = [
  { type: 'members', label: 'Members', desc: 'All profiles with status, contact and join dates.' },
  { type: 'cases', label: 'Cases', desc: 'Welfare claims with amounts, statuses and timelines.' },
  { type: 'invoices', label: 'Invoices', desc: 'Per-member billing with status and due dates.' },
  { type: 'payments', label: 'Payments', desc: 'Payments with channel, receipts and status.' },
  { type: 'dependents', label: 'Dependents', desc: 'Dependents with verification status.' },
  { type: 'attendance', label: 'Attendance', desc: 'Event attendance records.' },
];

export default function ReportsPage() {
  return (
    <div>
      <PageHeader
        title="Reports"
        subtitle="Downloadable exports generated by the reports API."
      />

      <p className="mb-6 max-w-3xl rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
        These links call <code className="rounded bg-amber-100 px-1">GET /api/reports?type=…&format=…</code>, which is
        built by the API agent. If a download returns 404, that report endpoint is not wired up yet.
      </p>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {TYPES.map((t) => (
          <Card key={t.type} title={t.label}>
            <p className="mb-4 text-sm text-slate-600">{t.desc}</p>
            <div className="flex gap-2">
              <a
                href={`/api/reports?type=${t.type}&format=csv`}
                className="inline-flex items-center rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700"
              >
                Download CSV
              </a>
              <a
                href={`/api/reports?type=${t.type}&format=pdf`}
                className="inline-flex items-center rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
              >
                Download PDF
              </a>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}
